import type { Project } from "./types";

export const PROJECTS_DATA: Project[] = [
  {
    id: 1,
    name: "Enterprise Dashboard",
    manager: "Alex Morgan",
    date: "Jan 12, 2026",
    status: "On Track",
    team: ["JD", "SK", "RL"],
    progress: 75,
    color: "bg-primary/10 text-primary",
  },
  {
    id: 2,
    name: "Mobile Banking App",
    manager: "Sarah Konor",
    date: "Feb 05, 2026",
    status: "At Risk",
    team: ["AM", "PK"],
    progress: 32,
    color: "bg-red-400/10 text-red-400",
  },
  {
    id: 3,
    name: "AI Content Engine",
    manager: "John Doe",
    date: "Dec 20, 2025",
    status: "Delayed",
    team: ["SM", "TQ", "LK"],
    progress: 45,
    color: "bg-amber-500/10 text-amber-500",
  },
  {
    id: 4,
    name: "Cloud Infrastructure",
    manager: "Mike Ross",
    date: "Jan 28, 2026",
    status: "On Track",
    team: ["DR", "ST"],
    progress: 92,
    color: "bg-emerald-500/10 text-emerald-500",
  },
  {
    id: 5,
    name: "E-commerce Redesign",
    manager: "Elena Gilbert",
    date: "Feb 10, 2026",
    status: "On Track",
    team: ["BH", "CW"],
    progress: 15,
    color: "bg-purple-500/10 text-purple-500",
  },
  {
    id: 6,
    name: "Security Audit v2",
    manager: "Chris Evans",
    date: "Nov 15, 2025",
    status: "Completed",
    team: ["BW", "BB"],
    progress: 100,
    color: "bg-blue-500/10 text-blue-500",
  },
];
